//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Articles = new HashSet<Article>();
            this.Questions = new HashSet<Question>();
            this.Quizzes = new HashSet<Quizze>();
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public byte[] Image1 { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Quizze> Quizzes { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
