//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class louisemc_tudorsEntities : DbContext
    {
        public louisemc_tudorsEntities()
            : base("name=louisemc_tudorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Quizze> Quizzes { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    }
}
