//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> ImageId { get; set; }
        public int QuizId { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Image Image { get; set; }
        public virtual Quizze Quizze { get; set; }
    }
}
