//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quizze
    {
        public Quizze()
        {
            this.Questions = new HashSet<Question>();
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] ImageId { get; set; }
        public Nullable<int> AnotherImageId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
